### ISSUE TITLE
Implementing conditional averaging 

### ISSUE THREAD

**Issue by asztalosors** [fusion-flap/flap#27]
Conditional averaging should be implemented. The routine should apply requested filtering to input signals. Return the conditional averaged signal bit as well as all the events that contributed to the averaging process. 

Point of discussion:
Further data processing, such as statistical analysis of all positive events should take place within the same code package or done separately?

**Comment by thelampire** [comment]
This is a good idea, it should be implemented in flap itself since it was aimed to be a general data analysis toolkit. Assignee? 

(I don't have time for it at the moment.)

**Comment by asztalosors** [comment]
I suppose once I get added to dev. team I can assign myself to it. I'll do the implementation.

**Comment by gergopokol** [comment]
The routine should be able to output the collection of positive events for external analysis (e.g. time-frequency analysis).

**Comment by sandorzoletnik** [comment]
If Ors does this it is fine for me, but please come with some proposal after checking what is availabe. At present the following is available:
select_intervals: Finds the events and creates a data object containing the (fixed length) intervals around the condition. 
slice_data can use this data object to cut these intervals from an n-dimensional data object (along a coordinate) and put the data into two dimensions: one across the intervals and one in the intervals. 
a summing operation in slice_data can average through the intervals to generate the conditionally averaged signal. It can also take minimum, maximum to show the variability.
Check out these in test_select_multislice():i n flap_tests.py

I think the above implements conditional averaging on multiple signals. What could be done additionally:
- Add RMS to summing 
- Add more conditions in select_interval. E.g. I wanted to implement the correlation-of-correlation which would base a condition on multiple signals
- Write a diff (or similar name) routine to calculate the waiting time between events
- Write a pdf routine to calculate probability distribution function
- select_intervals could put the amplitude of the event in the data of the output data object

**Comment by asztalosors** [comment]
I will create a branch from development and implement the requested changes and we can continue the discussion from there.
