### ISSUE TITLE
General indexing convention in matplotlib.pyplot.contour and np.meshgrid

### ISSUE THREAD

**Issue by thelampire** [fusion-flap/flap#30]
The issue I had with the contours was due to numpy's xy indexing style. If one creates a 2D matrix out of and X and Y vector in a way where it's indexed as [x_i,y_i], it is not going to be correctly indexed for a contour plot for example. There the indexing is [y_i,x_j], the same as with np.meshgrid. I checked the documentation and matplotlib actually uses the np.meshgrid. If one wants to visualize data directly from the flap.DataObject.coordinate('Device R')[0] and if it is a 2D array, it should be transposed when plotting with contour.

The data should still be indexed as d(x_i,y_j) which is weird.

What is going on? I don't understand the reasoning behind having contradictory indexing.

**Comment by sandorzoletnik** [comment]
Do you get correct plots? If yes, there is nothing to do here, transposing is handled by flap.plot. If the plot is not correct this is a bug.

**Comment by thelampire** [comment]
I think I am going to close this. matplotlib has a weird convention of using y,x when it comes to grids and x,y when it comes to data. y,x is somewhat understandable if one is thinking about matrices (row-->y, col-->x) but mostly I am only thinking about indices.
