### ISSUE TITLE
flap.list_data_objects()

### ISSUE THREAD

**Issue by thelampire** [fusion-flap/flap#33]
If I accidentally add a coordinate which has NaN values in it, flap.list_data_objects() fails with the following error message:

Traceback (most recent call last):

  File "<ipython-input-37-1abe57c0dab4>", line 1, in <module>
    flap.list_data_objects()

  File "/Volumes/GoogleDrive/My Drive/work/flap/flap/data_object.py", line 3673, in list_data_objects
    c_data, c_range_l, c_range_h = c.data(data_shape=data_shape,index=ind)

  File "/Volumes/GoogleDrive/My Drive/work/flap/flap/coordinate.py", line 765, in data
    "Interpolating for coordinate determination is not implemented yet.")

NotImplementedError: Interpolating for coordinate determination is not implemented yet.

I could probably fix this but I wonder if anybody else got this problem or not.

**Comment by thelampire** [comment]
The problem was related to not giving a shape to the coordinates. Why is that necessary? Shape can be easily gathered from np.asarray(array).shape. Can equidistant interpolation be realized by only giving it a different shape?

**Comment by sandorzoletnik** [comment]
Yes, there is a rationale for this described in the (preliminary) doc. If the shape equals to the actual shape of values then there is 1:1 correspondance between the coordinate values and the data points. If the shape is different the coordinate of the data points should be calculated from the given values using interpolation. This e.g. enables one to use a time dependent spatial coordinate system when the coordinates are slowly changing in time (like flux coordinate) without the need to give the coordinates for each time slice. However, as the error message says this function has not been implemented yet.

**Comment by thelampire** [comment]
I think this was the one I wanted to do. I mean the interpolation part. Actually I made it work now in the plot.py's animation part. I can visualize a video as a function of normalized flux surfaces, but it takes some time to calculate it.
