### ISSUE TITLE
Slicing takes forever after adding normalized flux coordinate changing in time

### ISSUE THREAD

**Issue by thelampire** [fusion-flap/flap#35]
After adding the normalized poloidal flux coordinate as a coordinate to GPI data, it takes 54 seconds to slice it to a given time range. Without having that coordinate in the data, slicing takes 0.11seconds.
The normalized flux coordinate data have the same amount of data points as the data have.

I can probably fix this but the fix needs to be approved because it is part of the main software.

**Comment by sandorzoletnik** [comment]
The coordinate is non-equidistant probably and assigns a value to all time instances. What do you have in the iInterpol option during slice? CLosest neighbour should be faster.

**Comment by thelampire** [comment]
The coordinates are indeed non-equidistant and their value is actually changing with time. However, there is a single spatial data point for each signal data point. No interpolation, or closest neighbor approximation would be necessary. If the data is sliced within 0.5s or less without the spatial data, I would expect twice the time for slicing twice the data. Not 53 times higher. No interpolation should take place when the size of the spatial coordinates is the same in some direction. For example, if the data is 60000 x 64 x 80 as the GPI is, and the flux coordinates are also 60000 x 64 x 80, then there is no point for interpolation. Furthermore, the spatial data doesn't / cannot have a time axis. I guess it makes sense, but then if I assign a 300 x 64 x 80 spatial coordinate to the 60000 images, would it assume that the start and end of the spatial coordinate is the same as the data?
Wouldn't it just give an error that the coordinate doesn't have the same shape as the data has?

**Comment by sandorzoletnik** [comment]
Na ezt nem értem.

Ha annyi koordináta érték van ahány adat pont akkor is lehet 
interpoláció a slice_data-ban. Ott closest neighbour-ra van állítva? 
Hogy slicolod, egy pontot veszel ki vagy sokat? Csinálnál egy 
list_data_objects-t az adatra és elküldenéd az eredményt meg a slice 
hívást?

Sanyi

--------------------------------------------------------
Dr. Sandor Zoletnik
Head of Research Unit
Wigner Research Centre for Physics (Wigner RCP)
Eurofusion Consortium, Hungarian Fusion Technology Platform
Letters: P.O.B. 49, H-1525, Budapest, Hungary
Phone: (36 1) 3922753
E-mail: zoletnik.sandor@wigner.mta.hu
--------------------------------------------------------

------ Original Message ------

**Comment by thelampire** [comment]
De miert kene akkor interpolacionak lennie? Mondj kerlek egy peldat, amikor ugyanannyi adatpont es ugyanannyi osszetartozo terbeli koordinata pont eseten szukseg lenne interpolaciora?

Itt vannak az eredmenyek:

list_data_objects:

-----------------------------
GPI(data_source:"NSTX_GPI" exp_id:"141918") data_title:"NSTX GPI data" shape:[59650,64,80][no error]
  Data name:"Signal", unit:"Digit"
  Coords:
Time [ms](Dims:0]) [<Equ.><R. symm.>] Start:  2.200E+02, Steps:  3.000E-03
Sample [n.a.](Dims:0]) [<Equ.><R. symm.>] Start:  0.000E+00, Steps:  1.000E+00
Image x [Pixel](Dims:1]) [<Equ.><R. symm.>] Start:  0.000E+00, Steps:  1.000E+00
Image y [Pixel](Dims:2]) [<Equ.><R. symm.>] Start:  0.000E+00, Steps:  1.000E+00
Device R [mm](Dims:1,2]) [<Equ.><R. symm.>] Start:  1.403E+03, Steps:  3.718E+00, -7.782E-01
Device z [mm](Dims:1,2]) [<Equ.><R. symm.>] Start:  7.054E+01, Steps:  1.809E-01,  3.066E+00
Device phi [a.u.](Dims:0,1,2, Shape:[59650,64,80]) [<R. symm.>] Val. range:  5.811E-01 -  1.291E+00
-----------------------------
PSIRZ_FOR_COORD(data_source:"NSTX_MDSPlus" exp_id:"141918") data_title:"NSTX MDSPlus data" shape:[128,65,65][no error]
  Data name:"\EFIT01::\PSIRZ", unit:"Wb/rad"
  Coords:
Time [s](Dims:0, Shape:[128]) [<R. symm.>] Val. range: -1.000E-02 -  5.250E-01
Device R [m](Dims:1, Shape:[65]) [<R. symm.>] Val. range:  1.000E-02 -  2.150E+00
Device z [m](Dims:2, Shape:[65]) [<R. symm.>] Val. range: -2.200E+00 -  2.200E+00
Sample [Wb/rad](Dims:0]) [<Equ.><R. symm.>] Start:  0.000E+00, Steps:  1.000E+00
Signal name [a.u.](Dims:, Shape:[1]) [<R. symm.>] Val:\EFIT01::\PSIRZ
Channel [a.u.](Dims:, Shape:[1]) [<R. symm.>] Val:1
mds description [a.u.](Dims:, Shape:[1]) [<R. symm.>] Val:\EFIT01::\PSIRZ
-----------------------------
SSIMAG_FOR COORD(data_source:"NSTX_MDSPlus" exp_id:"141918") data_title:"NSTX MDSPlus data" shape:[128][no error]
  Data name:"\EFIT01::\SSIMAG", unit:"Wb/rad"
  Coords:
Time [s](Dims:0, Shape:[128]) [<R. symm.>] Val. range: -1.000E-02 -  5.250E-01
Sample [Wb/rad](Dims:0]) [<Equ.><R. symm.>] Start:  0.000E+00, Steps:  1.000E+00
Signal name [a.u.](Dims:, Shape:[1]) [<R. symm.>] Val:\EFIT01::\SSIMAG
Channel [a.u.](Dims:, Shape:[1]) [<R. symm.>] Val:1
mds description [a.u.](Dims:, Shape:[1]) [<R. symm.>] Val:\EFIT01::\SSIMAG
-----------------------------
SSIBRY_FOR_COORD(data_source:"NSTX_MDSPlus" exp_id:"141918") data_title:"NSTX MDSPlus data" shape:[128][no error]
  Data name:"\EFIT01::\SSIBRY", unit:"Wb/rad"
  Coords:
Time [s](Dims:0, Shape:[128]) [<R. symm.>] Val. range: -1.000E-02 -  5.250E-01
Sample [Wb/rad](Dims:0]) [<Equ.><R. symm.>] Start:  0.000E+00, Steps:  1.000E+00
Signal name [a.u.](Dims:, Shape:[1]) [<R. symm.>] Val:\EFIT01::\SSIBRY
Channel [a.u.](Dims:, Shape:[1]) [<R. symm.>] Val:1
mds description [a.u.](Dims:, Shape:[1]) [<R. symm.>] Val:\EFIT01::\SSIBRY

A slice itt van meghivva:

    flap.plot('GPI',plot_type='animation',
              slicing={'Time':flap.Intervals(250.,260.)},
              axes=['Device phi','Device z','Time'],
              options={'Z range':[0,512],'Wait':0.0,'Clear':False})

**Comment by sandorzoletnik** [comment]
Nincs szükség interplációra, valamit félreértesz.

Na akkor konkrétan:
És ebben a slice vagy a plot megy lassan?
Ha a slice, akkor:
Csak akkor megy lassan mikor a fluxus koordinátát hozzáadod?
Próbáld meg a slice_data option-okhoz betenni, hogy 'Interpolationá: 
'Closest value'

Néztem a kódot, nem tudom mit csinálna ilyen sokáig egy síma array-ból 
egy slice változóval kellene kiszedje az adatokat pillanat alatt. Valami 
hülyeség van itt. Ha leteszed az adat objektumot egy save-el valahova és 
elküldöd a kódot is akkor bele tudok nézni, hogy mit csinál. Ha csak 
akkor lassú mikor a fluxus koordinátát hozzárakod akkor valahol a 
data_object.py-ban a __check_coords_after_multi_slice()-ban tölti az 
időt, de nem értem miért.


Sanyi

--------------------------------------------------------
Dr. Sandor Zoletnik
Head of Research Unit
Wigner Research Centre for Physics (Wigner RCP)
Eurofusion Consortium, Hungarian Fusion Technology Platform
Letters: P.O.B. 49, H-1525, Budapest, Hungary
Phone: (36 1) 3922753
E-mail: zoletnik.sandor@wigner.mta.hu
--------------------------------------------------------

------ Original Message ------

**Comment by thelampire** [comment]
A closest value van beallitva default-nak. 
A plot.py-nak a 953. sora lassu:
d = data_object.slice_data(slicing=slicing, summing=summing, options=slicing_options)
Kb ugyanannyi ideig tart, mint amig hozzaadom a koordinatat. De az utobbi ertheto, mert ott a 128x64x64-es EFIT adatot 64000x58x80-as-ra interpolalom kb. manualisan. Eloszor a 128db EFIT-et rakom ra a GPI racsra aztan meg az EFIT idovektorat interpolalom at a GPI-ra. Ez nyilvan lassu.

Most jatszok a profile-lal, ami elvileg megmondja, hogy melyik sor mennyi ideig tart.

**Comment by thelampire** [comment]
Elvileg ez tart a legtobb ideig:
__check_coords_after_simple_slice

De itt elakadtam egy kicsit.

**Comment by thelampire** [comment]
A coordinate.py 748,749-es sora tart ezer evig:

                value_index_arrays = submatrix_index(np.array(self.values).shape, value_index)
                value_mx = np.array(self.values)[value_index_arrays]

**Comment by thelampire** [comment]
Ugy latom, hogy az a problema, hogy nem slice-olva van a koordinata, hanem egyesevel kibanyaszva. Sajnos ehhez nem ertek, abszolut nem ertem, hogy hogyan van az adat slice-olva. De az biztos, hogy ebben az esetben a koordinata-t is ugyanugy kene csinalni, mert az pillanatok alatt megvan.

**Comment by thelampire** [comment]
Meg egy dolog. Bocsanat a sok spam-ert. Egy rovidebb slice-olas nem tart sokaig, de egyszer valamiert a teljes adatot atcsinalja ugyancsak teljes adatta:
A fenti sorok utan ezeket a printeket beirva:
                print(np.asarray(value_index_arrays).shape)
                print(np.asarray(values.shape)
                print(value_mx.shape)
Ez az eredmeny.
(3, 59650, 64, 80)
(59650, 64, 80)
(59650, 64, 80)
Utana, mikor tenylegesen levagja/levagta mar:
(3, 1, 64, 80)
(3333, 64, 80)
(1, 64, 80)

**Comment by thelampire** [comment]
Sanyi, ez nagyon kellene. Nem latom at ezt a submatrix_index-et annyira, hogy a visszaadott tuple-t at tudjam irni slice-ra. Nem latom, hogy ezt miert igy kell csinalni, de az biztos hogy lehetne gyorsabban. Nagy tomboknel nagyon nagyon lassu.

**Comment by sandorzoletnik** [comment]
Máté, most konferencia van és cikk review határodőm van ma, holnap meg 
reggel TV és 2 tárgyalás a konferencián. Esetleg este rá tudok nézni. 
Nem tudtam végignézni az emailjeidet pár napja, de remélhetőleg benne 
van minden info.

Sanyi

--------------------------------------------------------
Dr. Sandor Zoletnik
Head of Research Unit
Wigner Research Centre for Physics (Wigner RCP)
Eurofusion Consortium, Hungarian Fusion Technology Platform
Letters: P.O.B. 49, H-1525, Budapest, Hungary
Phone: (36 1) 3922753
E-mail: zoletnik.sandor@wigner.mta.hu
--------------------------------------------------------

------ Original Message ------

**Comment by thelampire** [comment]
Semmi gond, talaltam egy koztes megoldast ugy tunik slice-okkal, de szerintem nem altalanos elegge. Egyelore nekem jo lesz, hogy ne a fel napom a varakozassal menjen.

**Comment by thelampire** [comment]
A submatrix_index sora helyett ezt hasznalom:
                value_index_arrays=[]
                for i in range(len(np.array(self.values).shape)):
                    value_index_arrays.append(slice(min(value_index[i]),max(value_index[i])+1))
                value_mx = np.array(self.values)[tuple(value_index_arrays)]
Negyszer gyorsabb. Viszont csak folytonos slice-ot tud, ritkitott matrixot nem. Van meg egy helyen submatrix_index hivas. Azt is lecserelem magamnak.

**Comment by sandorzoletnik** [comment]
Dear FLAP User,

Kösz a spam-ekért azt hiszem értem mi történik. Az adat kibányászás a 
numpy általam ismert lehetséges módján van, tehát nem  egyesével ahogy 
Te írtad. Az a helyzet, hogy egy N dimenziós tömbből kell kivenni egy M 
dimenziós altömböt az egyes irányokban tetszőleges elemekkel. Ezt 
szerintem úgy lehet csak megcsinálni numpy-ban, hogy elő kell állítani N 
darab mátrixot, mindegyik shape-je az eredmény mátrix shape-el egyezik 
meg és az i-edikben a kiinduló mátrix kivánt elemeinek i-dik indexei 
vannak. Ezen sokat vackoltam, de általánosan nem találtam mást. Erre 
csináltam a submatrix_index nevű rutint ami előállítja ezeket a 
mátrixokat. Nagy tömböknél ez valóban sok memóriát igényel és 
valószínűleg ezért lesz nagy tömbökre lassú.

Most kicsit elbizonytalanodtam, hogy lehetne-e az index array-be 
sliceokat keverni ahogy Te csináltad. Hitem szerint a value_index-ben 
kell legyenek slice-ok, mert ha slice-al le lehet írni valamit akkor 
azzal írom le. Meg tudnád ezt nézni? Azért is írtam, hogy legjobb lenne 
ha le tudnál rakni  a beam-re egy adat és program csomagot amin ezt 
nézni tudnám.

Üdv,

Sanyi

--------------------------------------------------------
Dr. Sandor Zoletnik
Head of Research Unit
Wigner Research Centre for Physics (Wigner RCP)
Eurofusion Consortium, Hungarian Fusion Technology Platform
Letters: P.O.B. 49, H-1525, Budapest, Hungary
Phone: (36 1) 3922753
E-mail: zoletnik.sandor@wigner.mta.hu
--------------------------------------------------------

------ Original Message ------

**Comment by thelampire** [comment]
This feature needs to be tested with other data sources. It is working for me for all the 2,3 dimensional objects. The current implementation is pushed to thelampire-patch-3 along with the commented out older solution. i am closing this issue as I believe that the optimal solution is the one I implemented with the slices.
