### ISSUE TITLE
IMPORTANT: from .tools & .coordinate import * warnings

### ISSUE THREAD

**Issue by thelampire** [fusion-flap/flap#36]
These warnings pollute the entire Spyder warning frame since Spyder cannot recognize where the objects and functions are if they are imported in the following way:

from .tools import *
from .coordinate import *

This also makes debugging and understanding the code much more difficult.

Would it be possible to fix this?

I know that instead of e.g. Intervals we would need to use flap.coordinate.Intervals or flap.Intervals but it would be better to understand the code and also to find the corresponding parts.

What do you think?
This can be easily fixed by ctrl + r replacement of e.g. Intervals with flap.Intervals.

**Comment by sandorzoletnik** [comment]
I don't understand this. First I get no warnings, where do you get warnings? Second if an error happens I can go the problem with one click. Can you elaborate the problem?

**Comment by thelampire** [comment]
In spyder, on the left, there is always this warning for .tools and .coordinate functions:
maybe undefined or defined from star imports: .tools
My solution above is not good since I would import the package within the package, but still, it is annoying that the right scrollbar is filled with the yellow warning place signs.
![Screen Shot 2019-09-25 at 2 43 03 PM](https://user-images.githubusercontent.com/52581826/65630379-50d04300-dfa3-11e9-8e51-40536a27bffa.png)

**Comment by sandorzoletnik** [comment]
The problem is thatn spyer puts there so many studid warnings that I 
gave up with it. For some time I tried to get rid off warnings, but I 
don't think is is useful.

Cheers,

--------------------------------------------------------
Dr. Sandor Zoletnik
Head of Research Unit
Wigner Research Centre for Physics (Wigner RCP)
Eurofusion Consortium, Hungarian Fusion Technology Platform
Letters: P.O.B. 49, H-1525, Budapest, Hungary
Phone: (36 1) 3922753
E-mail: zoletnik.sandor@wigner.mta.hu
--------------------------------------------------------

------ Original Message ------

**Comment by thelampire** [comment]
I found the solution. It works just as with the .config import:
import flap.tools as tools
import flap.coordinate as coordinate

In this way, there are no warnings and one can get a better view of the code. I am going to submit a new commit into thelampire-patch-02.

**Comment by thelampire** [comment]
I also found other import related issues which kind of worked so far. Further submits are coming.

**Comment by thelampire** [comment]
I found tons of error in the codes after I changed the star imports to actual imports. Until now they were only warnings and the errors were not triggered because those parts of the code were not invoked at any time. This needs to be fixed for all the codes and used in the future. I am working on it at the moment.

**Comment by thelampire** [comment]
I finished fixing all the files in flap. Please review the thelampire-patch-2 and merge it into the development branch. All the tests are running after the modifications.
I think there should be more test procedures defined as I have found around 10 typo errors which would have showed up as error if those parts of the code were run at any time. I added some comments at the modified lines.
Also, you can check all my modifications on the web. I would probably do that if I was you because relying on just the comments with such a big commit is probably not the best thing to do.

**Comment by thelampire** [comment]
The __init__.py files all needs to be updated, as well. I read it at multiple places, that star imports are really bad practice and they all mentioned the same concerns I was facing.
I close this issue for now, but we can reopen something similar when (or if) we create a package.
