### ISSUE TITLE
variance calculation with summing 'mean'

### ISSUE THREAD

**Issue by mvecsei** [fusion-flap/flap#37]
I believe there is an error when the summing is called with the 'Mean' description. The code normalizes the _error_  attribute with _n_ (number of points) and not _sqrt(n)_. Moreover, it is not taken into account that the values have also a variance relative to the output of the 'Mean' summing. Did some calculations and I believe it is correct now.

**Comment by sandorzoletnik** [comment]
This looks good, I merged it into development. I did not remove branch error_calc

**Comment by sandorzoletnik** [comment]
This problem I had as well, therefore I clone to a directory with different name. Python recoginizes a directory with name flap as a module irrespective whether there is an __init__ in it. I agree to move the code from flap directory to the main and remove flap. If no one objects within a few days I can do it.
