### ISSUE TITLE
Further enhancement proposals

### ISSUE THREAD

**Issue by thelampire** [fusion-flap/flap#40]
I would like to propose the following enhancements to the code:

- An option to return the default_options dictionary keys with comments. This would be like a help module, so users don't have to look up the actual code to find the options.
- Some kind of standardized GUI. I could look up OMFIT where they have it.
- A user manual embedded in the code which could be read by an automatic user manual generator (forgot its name).
- A well documented object structure and dependancies (probably could be done automatically).

**Comment by thelampire** [comment]
For the plot.py:

It would be great to have a subplot where one can plot a series of plots which would show ip, p_NBI, n_e etc. and a vertical line of time point were the animation is currently. For now it is quite cumbersome to plot the D_alpha and the animation side by side. Animation wants to update the D_alpha if the video is not handled in the right way.

**Comment by mvecsei** [comment]
I actually started doing a GUI for the density analysis. It was intended to be a very basic one and then got more complicated every time I tried to do something new. So at least I have some ideas about this. One question is which package we should be using. I was using Qt for this one, and I was really satisfied with how it worked, but maybe Tk is preferable.

The other points are valid as well, I think @Csega knows more about the standardized manual.

**Comment by sandorzoletnik** [comment]
You can use plt.subplot and just make the plots. If you keep the plotID returned by flap.plot, you can also plot into each of the plots later. Look into flap_tests, there are examples.

I used TK, but probably Qt is preferred.

**Comment by thelampire** [comment]
For the plot.py/animation:

There should be a text box where the time can be entered and the video would resume from there. (Just a reminder for myself as I am the author of that part (which is still not merged into development)

**Comment by thelampire** [comment]
A standardized plot saving (.eps, .ps, .png, .pdf) should be a nice option just as video saving is available for anim-image and anim contour. 
Matplotlib offers .savefig() but there might be a better way.
I know that one can save the plot with the GUI, but that doesn't work in a loop if I want to save multiple plots.
Also, it would be nice to have video saving not only with cv2 but with something less sophisticated (e.g. I could't install OpenCV on the mac).

**Comment by thelampire** [comment]
Plotting should be available in different units e.g. ms, s or Hz kHz etc. tools.time_unit_translation and tools.spatial_unit_translation could be used for it. Time unit translation could be modified so it could accept frequency, as well. There shouldn't be too many functions for unit conversions/translations.

**Comment by thelampire** [comment]
For the plot.py cv2 video saving:
There should be an option of "Video saving only" where the animation is not plotted but only saved in a video file. I tried to implement this by not running the plt.show() when the _options['Video saving only'] is True but then there is nothing in the buffer and no video is produced.
This feature would be quite useful as the computer cannot be used at all when an anim-image or anim-contour is running.

**Comment by thelampire** [comment]
For plot.py simple plots:

It would be useful if it was possible to plot vertical lines on the plots. It could be an input in plot.py options as such:

options['Vertical lines']=[[x1,'blue'], [x2,'red']] etc.

Vertical lines can be drawn with the following code:

def vertical_line(x, color=None):
    
    ax = plt.gca()
    xmin, xmax = ax.get_xbound()

    xmin = xmax = x
    ymin, ymax = ax.get_ybound()

    l = mlines.Line2D([xmin,xmax], [ymin,ymax], color=color)
    ax.add_line(l)
    return l

This is mediocre, but works for a single plot. It could be modified to work for the plot_IDs, but I do not understand that part of the flap plot yet.

**Comment by sandorzoletnik** [comment]
My plan was to have an option to be able to plot multiple polygons in the anim plots so as they go into the video. For normal plots this is easy to do after the plot as you show.

**Comment by thelampire** [comment]
I deleted a bunch of comments which have already been realized. I also implemented a general path and contour overplotting which replaced the EFIT overplot. It is much more elegant and does the same. Also for anim-image and anim-contour. THe futher implementation is going to work for image and contour, as well.

**Comment by thelampire** [comment]
I deleted also a bunch of comments which have already been realized.

**Comment by thelampire** [comment]
A module needs to be developed to process turbulence data with large channel numbers (like GPI). As long as I have time I am going to start working on this.
This is just a reminder, that this needs to be done.

**Comment by thelampire** [comment]
plot.py:
It would be great if 2D plotting was available for dependent time axis coordinates, as well.
E.g.: I have CPSD calculated for a dataset which has Device R and Device z (dependent) The third axis is Frequency. I cannot plot an animation with axes=['Device R', Frequency, Device z]. I understand that for irregularly shaped grids, this would look weird at some places, but it would be useful to go through slices of data without plotting the slices one by one.

I cannot really work on this at the moment, I need to produce some results. Please somebody take this issue.

**Comment by thelampire** [comment]
These features were either implemented or were not important enough in the last year. Closing the issue.
