### ISSUE TITLE
flap.list_data_objects() \n is not interpreted.

### ISSUE THREAD

**Issue by thelampire** [fusion-flap/flap#41]
When using list_data_objects() it can be difficult to figure out the objects, because \n is not interpreted and everything shows up as one line.

**Comment by sandorzoletnik** [comment]
I can't do much with this. If you print the text it is interpreted. Use
d=flap.list_data_objects() 
which prints on the screen. Alternatively you can use
print(flap.list_data_objects(screen=False))
