### ISSUE TITLE
Warning at 'import flap'

### ISSUE THREAD

**Issue by thelampire** [fusion-flap/flap#42]
This warning is displayed all the time, when flap is imported but not flap_defaults.cfg is present:
'Warning: could not read configuration file.'
I think this should be more intuitive, something like: "Warning: flap_defaults.cfg is not present. Please provide a configuration file with flap.config.read(filename=filename)".

**Comment by sandorzoletnik** [comment]
Done, you get this message:
Warning: could not read configuration file flap_defaults.cfg.
Default location of configuration file is working directory.
