### ISSUE TITLE
data_object get_data error handling

### ISSUE THREAD

**Issue by thelampire** [fusion-flap/flap#48]
The data object get_data function cannot be debugged. It is nested within a try...except frame and whenever an error occurs within, the only this data_object does is that it is trying to call the f function without a data_source. This shouldn't be nested in there.

The solution: TypeError --> Keyerror (Line 3772, thelampire-patch-02 rev. 31)

**Comment by sandorzoletnik** [comment]
Improved error handling, it will call the function without data_source only if the data_source keyword was the problem.
