### ISSUE TITLE
slicing along a constant coordinate 

### ISSUE THREAD

**Issue by mvecsei** [fusion-flap/flap#5]
Slicing along a constant coordinate is not yet implemented. FLAP could return the original dataobject in this case.

**Comment by sandorzoletnik** [comment]
Done, returning original object without raising error.

**Comment by mvecsei** [comment]
I am still getting the same error for all branches.

**Comment by mvecsei** [comment]
I am still getting the same error for all branches.

**Comment by mvecsei** [comment]
Nope, sorry I made an error
