### ISSUE TITLE
No _acf function in spectral_analysis.py

### ISSUE THREAD

**Issue by thelampire** [fusion-flap/flap#58]
I didn't find any autocorrelation calculation tools nor an option at flap.ccf to calculate the autocorrelation. In theory I could just calculate all the ccf functions in the video and select the autocorrelation ones, but that would take too much time.

Is there a reason why flap.acf is not implemented?

**Comment by sandorzoletnik** [comment]
I was thinking about this, as we have an APSD and CPSD. But it did not look very interesting to calculate the ACFs. It is possible to do this, needs a few hours, but there are other issues before it.. Let's keep this as an issue.

**Comment by thelampire** [comment]
I believe this can be done by setting the reference and the data object to the same and normalization to False. This doesn't need to be a separate method I believe.
