### ISSUE TITLE
Fringe jump correction

### ISSUE THREAD

**Issue by thelampire** [fusion-flap/flap#68]
Would it be possible to implement some kind of fringe jump correction for the CPSD phase calculation? My plots look weird with the +-Pi jumps.
![Screen Shot 2019-11-22 at 8 06 24 PM](https://user-images.githubusercontent.com/52581826/69470299-9622ae00-0d63-11ea-8b18-fb171db9974f.png)

Also, does anybody have any idea what could a linear phase slope mean in spatial coordinates? If there is a linear frequency - phase slope, that's propagation. But what does linear radial coordinate - phase dependence show?

**Comment by gergopokol** [comment]
A common solution is to plot the angles with a circularly smooth color scale.

**Comment by gergopokol** [comment]
Linear spatial phase function might indicate different phenomena depending on the time behaviour. Toy modells come handy for this purpose.

**Comment by thelampire** [comment]
This hasn't come up again, Gergo's suggestion solved the problem. Closing the issue.
