### ISSUE TITLE
Cross-correlation function calculation

### ISSUE THREAD

**Issue by thelampire** [fusion-flap/flap#72]
When cross-correlation functions are calculated, the covariance should be divided by both autocorrelation functions, the plot channel's and the reference channel's.

- I don't see this in the code. Could you point me to the line in spectral_analysis.py which does both channel normalization.
- The magnitude of the cross-correlation functions are not correct. They can be below -1 or over 1 which shouldn't be the case for a normalized function.
- Is there an option to compensate for the peak appearing do to photon noise in the center of the ACF? This can mess up the correlation coefficient of the CCF quite a bit.

**Comment by sandorzoletnik** [comment]
Look for calc_acf in the code. This is a flag and tells that the ACFs should be calculated separately. This is the case then there is a ref input. Then look for "if  (norm)", there you can see how the ACFs are used.

Unfortunately the photon peak correction is not there. Could be done as is was in FLIPP.

**Comment by thelampire** [comment]
Issue raised separately for the photon peak subtraction, the rest is answered. I am closing this issue.
