### ISSUE TITLE
Modified or not modified original data object

### ISSUE THREAD

**Issue by thelampire** [fusion-flap/flap#75]
For some reason I thought that e.g. flap.slice_data or flap.filter_data would modify the data of the original data_object if there is no output name given. I guess then it doesn't do anything if it is not assigned to any variable. Is this correct?

**Comment by sandorzoletnik** [comment]
Yes, this is correct. Originally the input data object was modified, but this was not intuitive I think, therefore I removed. If you want the original data to be modified you have to specify the same name for output_name
