### ISSUE TITLE
User's Guide - beginner's experience update

### ISSUE THREAD

**Issue by martonvavrik** [fusion-flap/flap#81]
Update the users guide to reflect solutions for easy set-up -  from a beginner's perspective
Problematic issues:
- Importance of flap.Coordinate.dimension_list
- Useful checking attributes (eg. flap_object.coordinate('cname') )
- Importance of flap.DataObject.data_shape
- Importance of flap.Coordinate.shape (eg. Slicing)
- Expand the description for flap.DataObject

**Comment by martonvavrik** [comment]
Attached proposal for the issue. Additions in green, deletions in red. Table of contents updated.
[FLAP_V1.11_Users_Guide_v1.69_issue#81.docx](https://github.com/fusion-flap/flap/files/4404020/FLAP_V1.11_Users_Guide_v1.69_issue.81.docx)

**Comment by gergopokol** [comment]
Word docs should be changed first with the "Follow changes" switched on. Should afterwards discuss if all necessary clarifications are included.

**Comment by sandorzoletnik** [comment]
These changes have been implemented (mostly) and version 1.70 contains them. One note: the exp_ID element is not necessarily string, the type is dependent on the data source.
