### ISSUE TITLE
flap.get_data_object inconsistency

### ISSUE THREAD

**Issue by thelampire** [fusion-flap/flap#82]
As far as I know, the flap.get_data_object should return a new object whereas the flap.get_data_object_ref should return a reference to the existing one. This is not the case. The copy.deepcopy returning is only implemented for the get_data_object when there is a keyerror and  the resulting nlist length is 1 which I believe happens, when there is an object without an exp_id for some reason. I think line 3510 should be d = copy.deepcopy(self.__data_objects[_name]).

**Comment by sandorzoletnik** [comment]
Indeed this was a bug, fixed now in master and development branches
