### ISSUE TITLE
flap save and load not working properly

### ISSUE THREAD

**Issue by thelampire** [fusion-flap/flap#83]
flap save is not saving the data object along with its name but saves it with "FLAP any data"
flap load is not loading the data object into the FLAP storage.

I tried this with a single data object for a single shot (exp_id) There seems to be some complicated stuff going on along with the save. The load seems simple enough but still, there is no data object loaded into the storage.

**Comment by sandorzoletnik** [comment]
I don't understand this, look at test_saveload() in flap_tests. 

Here is a manual test:
import flap
d=flap.DataObject()
flap.add_data_object(d,'DDD')
x=flap.list_data_objects()
flap.save('*','save.dat')
flap.delete_data_object('*')
x=flap.list_data_objects()
flap.load('save.dat')
x=flap.list_data_objects()

DDD is saved and than reloaded to the storage.

**Comment by thelampire** [comment]
I saved it with flap.save(flap.get_data_object('GPI_CCF_F_BY_F'), filename='139901_GPI_CCF_F_BY_F.pickle')
This will not save the data object name in the storage, because a new unstored object is created when calling get_data_object. So this is resolved now, it is working, when I use the object name 'GPI_CCF_F_BY_F'.
Thank you for the help.
