### ISSUE TITLE
anim-image, anim-contour is not working in matplotlib 3.4.1

### ISSUE THREAD

**Issue by thelampire** [fusion-flap/flap#86]
The plot types in the title are not working in the new versions of matplotlib. I get this error:

ValueError: Single argument to subplot must be a three-digit integer, not AxesSubplot(0.125,0.11;0.775x0.77)

I will try to resolve the issue.

**Comment by sandorzoletnik** [comment]
The current flap environment uses Matplotlib 3.3.1, I have not seen a problem with that.

**Comment by thelampire** [comment]
I think there is something wrong with my setup. I'll let you know when I'm able to figure it out. The problem might has to do with macOS.

**Comment by thelampire** [comment]
I managed to fix this problem. I am still not sure whether it is macOS or a general problem with the new matplotlib. The solution was to comment out the following line in the anim-image/anim-contour section:

plt.subplot(_plot_id.base_subplot)

I cannot write a line number, because my branch still hasn't been merged with the development one. I think we should do this at some point in the near future.

**Comment by thelampire** [comment]
> The current flap environment uses Matplotlib 3.3.1, I have not seen a problem with that.

I am closing this as this issue has been resolved in a version. I implemented the same fix in mine independently.
